apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
    name: iot-simulator.0.1.0
    namespace: placeholder
    annotations:
        categories: "Streaming & Messaging"
        certified: "false"
        description: An IoT device simulator, simulating producers and consumer for Eclipse Hono
        containerImage: ${ADDRESS_SPACE_CONTROLLER_IMAGE}
        createdAt: 2019-03-19T00:00:00Z

spec:
  maturity: beta
  displayName: IoT simulator
  description: >
    Foo bar
  version: 0.1.0
  keywords: ['iot', 'messaging', 'amqp', 'mqtt', 'http']
  labels:
    app: iot-simulator
  selector:
    matchLabels:
      app: iot-simulator

  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false

  install:
    strategy: deployment
    spec:

  customresourcedefinitions:

    owned:
    - group: iot.dentrassi.de
      kind: SimulatorConsumer
      name: simulatorconsumers.iot.dentrassi.de
      version: v1alpha1
    - group: iot.dentrassi.de
      kind: SimulatorProducer
      name: simulatorproducers.iot.dentrassi.de
      version: v1alpha1

    required:
    - name: monitoring.coreos.com
      version: v1
      kind: Prometheus
    - name: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
